[package]
name = "ferriki"
version = "0.1.0"
description = "Reusable native Rust syntax highlighter with TextMate grammars"
readme = "README.md"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
publish = ["crates-io"]

[dependencies]
ferriki-asset-gen = { version = "0.1.0", path = "../ferriki-asset-gen" }
ferriki-textmate = { version = "0.1.0", path = "../ferriki-textmate" }
serde = { workspace = true }
serde_json = { workspace = true }

[lints]
workspace = true
